{"name": "test_purchase_apply", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\nCase\\test_02_purchase.py:15: AssumptionFailure\n>>\tpytest.assume(num2-num1 == 1)   # 断言新增之后页面上会多一条数据\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               Case\\test_02_purchase.py:15: AssumptionFailure\nE               >>\tpytest.assume(num2-num1 == 1)   # 断言新增之后页面上会多一条数据\nE               AssertionError: assert False\n\nD:\\py3\\lib\\site-packages\\six.py:718: FailedAssumption"}, "description": "新增请购单测试用例", "start": 1723457617847, "stop": 1723457624789, "uuid": "33c5822e-3409-46b7-b654-716a3be7fe4f", "historyId": "bb48625be43c6856f2ac59236cc86c69", "testCaseId": "0d18d978dfc1aa2a0b3c33761d477194", "fullName": "Case.test_02_purchase#test_purchase_apply", "labels": [{"name": "parentSuite", "value": "Case"}, {"name": "suite", "value": "test_02_purchase"}, {"name": "host", "value": "LAPTOP-J99CE7C3"}, {"name": "thread", "value": "49044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Case.test_02_purchase"}]}